apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  selector: projectcalico.org/namespace in  {'default', 'advanced-policy-demo'}
  types:
  - Ingress
  - Egress